# Generated by Django 3.2.5 on 2021-07-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='course_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='course_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='course_subject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
