# Generated by Django 3.2.5 on 2021-07-22 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_completeted_date_assignment_completed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='completed_date',
        ),
    ]
