# Generated by Django 3.2.5 on 2021-07-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210723_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
    ]
