# Generated by Django 3.2.5 on 2021-07-22 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_assignment_completed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='teacher',
        ),
    ]
