# Generated by Django 3.2.5 on 2021-07-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210724_1620'),
        ('main_app', '0004_remove_assignment_teacher'),
    ]

    operations = [
    ]
