# Generated by Django 3.2.5 on 2021-07-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_merge_20210724_1913'),
        ('main_app', '0005_merge_20210724_2020'),
    ]

    operations = [
    ]
