# Generated by Django 3.2.5 on 2021-07-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_assignment_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='teacher',
            new_name='user',
        ),
    ]
