# Generated by Django 3.2.5 on 2021-07-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_classroom_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='assignments',
            field=models.ManyToManyField(to='main_app.Assignment'),
        ),
    ]
