# Generated by Django 3.2.5 on 2021-07-28 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_profile'),
        ('main_app', '0012_auto_20210728_0104'),
    ]

    operations = [
    ]
