# Generated by Django 3.2.5 on 2021-07-30 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_photo'),
        ('main_app', '0017_auto_20210729_1951'),
    ]

    operations = [
    ]
